# Generated by Django 5.1.6 on 2025-02-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Hyväksytty'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Viesti'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lähetysaika'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Nimimerkki'),
        ),
    ]
