# Generated by Django 5.1.6 on 2025-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_alter_message_approved_alter_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
